-- The FontStruction “HD44780A00 5x8”
-- (https://fontstruct.com/fontstructions/show/1850879) by “Lord Nightmare” is
-- licensed under a Creative Commons Attribution Share Alike license
-- (http://creativecommons.org/licenses/by-sa/3.0/).
-- “HD44780A00 5x8” was originally cloned (copied) from the FontStruction
-- “HD44780 5x8” (https://fontstruct.com/fontstructions/show/1724841) by
-- “Lord Nightmare”, which is licensed under a Creative Commons Attribution
-- Share Alike license (http://creativecommons.org/licenses/by-sa/3.0/).